### ISSUE TITLE
update 3d models with new stl

### ISSUE THREAD

**Issue by ldirko** [ldirko/Splendida-Fibonacci-256-demoreel#10]
for not forgot

**Comment by ldirko** [comment]
made https://www.thingiverse.com/thing:4791860 and in project folder

**Comment by qawsed55** [comment]
чтобы не флудить сильно: корпус это хорошо, но важно, чтобы по-уму все остальное было )
https://hackaday.com/2017/01/20/cheating-at-5v-ws2812-control-to-use-a-3-3v-data-line/
Суть в том, что этими диодами логическая единица воспринимается на уровне 0.7 умножить на Vпитания (вольт) (0.7*5=3.5В ).
При использовании ESP, у нас логика 3.3В, что на границе дозволенного и могут возникнуть трудности.
По ссылке - простое решение как увеличить уровень логической единицы, так сказать при помощи нулевого пикселя.
Насколько я понимаю, на выходе микросхема регенерирует сигнал. Поэтому, нам важно лишь на первый диод подать гарантированно распознаваемый сигнал, а дальше микросхема всё сделает сама.
Вот мы и уменьшаем обычным диодом напряжение питания на нулевой пиксель, сигнал 3.3В успешно распознается, а дальше уже выплевывается в ленту 5-ти вольтовая логика.
Рекомендую добавить или описание этого нуанса, или даже внедрить в код возможность использования нулевого пикселя (как вообще отдельнго элемента).

**Comment by ldirko** [comment]
> чтобы не флудить сильно: корпус это хорошо, но важно, чтобы по-уму все остальное было )
> https://hackaday.com/2017/01/20/cheating-at-5v-ws2812-control-to-use-a-3-3v-data-line/
> Суть в том, что этими диодами логическая единица воспринимается на уровне 0.7 умножить на Vпитания (вольт) (0.7*5=3.5В ).
> При использовании ESP, у нас логика 3.3В, что на границе дозволенного и могут возникнуть трудности.
> По ссылке - простое решение как увеличить уровень логической единицы, так сказать при помощи нулевого пикселя.
> Насколько я понимаю, на выходе микросхема регенерирует сигнал. Поэтому, нам важно лишь на первый диод подать гарантированно распознаваемый сигнал, а дальше микросхема всё сделает сама.
> Вот мы и уменьшаем обычным диодом напряжение питания на нулевой пиксель, сигнал 3.3В успешно распознается, а дальше уже выплевывается в ленту 5-ти вольтовая логика.
> Рекомендую добавить или описание этого нуанса, или даже внедрить в код возможность использования нулевого пикселя (как вообще отдельнго элемента).

если честно, у меня около 6 проектов на диодах дома, на Wemos, NodeMcu и Anom5. ни с одной из них не имел проблем с глюками логики, нулевой пиксель это все-таки извращение, если есть проблемы – ставим левел шифтер, нет проблем – работаем как есть. Каждый решает сам, и имхо, есть стандартные решения проблемы. Если заложить в код нулевой пиксель, это вызовет недоумение у пользователя. Что это? Зачем?

**Comment by qawsed55** [comment]
Согласен. Я тож много перепробовал, и вроде как он излишен. Но, как говорится: "береженого бог бережет - сказала монашка, надевая презерватив на свечу". Так и в этом случае - гарантировать гарантированный уровень логики. Ну, чтоб наверняка )
